### ISSUE TITLE
Support delta updates when updating via the API

### ISSUE THREAD

**Issue by ivan-diachenko-td** [velopack/velopack#595]
Right now, Velopack only [supports](https://github.com/velopack/velopack/blob/2b4a2e130bc1802e8ed25108fde701aba5cbbf96/src/lib-rust/src/manager.rs#L273) full updates when updating via the API. If the distribution URL provides only a delta package instead of a full nupkg, the tool will return a 404 error when checking for updates. It would be nice to have delta updates as well.

**Comment by caesay** [comment]
Fixed by #651

**Comment by ivan-diachenko-td** [comment]
@caesay, the issue is still there, I mean you still check only Full packages: https://github.com/velopack/velopack/blob/1d5c984c143a4e8ca0030613e69e8bb113854b61/src/lib-rust/src/manager.rs#L296

**Comment by caesay** [comment]
@ivan-diachenko-td The code you pointed out only identifies the `latest_version`. Slightly further in the file, we call `create_delta_update_strategy` which will identify the delta packages needed to update to the `latest_version`. If you are having an issue, please open a new issue and provide logs. The logs will explain if full updates or deltas are used, and why.
